steps:
  - name: build
    image: elixir:1.7
    commands:
      - mix do local.rebar --force, local.hex --force
      - MIX_ENV=test mix do deps.get, coveralls.json
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: dymo_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Check code formatting, linting and dialyze it using latest elixir.
  - name: checks
    image: elixir:1.7
    commands:
      - mix do local.rebar --force, local.hex --force
      - MIX_ENV=dev mix do deps.get, format --check-formatted, credo --all

  - name: slack-notify
    when:
      status: [success, failure]
    image: plugins/slack
    secrets: [slack_webhook]
    channel: ci
    username: Drone
    template: >
      [{{repo.name}}:{{build.branch}}]
      <{{build.link}}|Build {{truncate build.commit 8}}> by {{build.author}}
      was a {{build.status}}.

  # Upload coverage reports, only for the latest elixir.
  - name: codecov
    when:
      status: [success]
    image: robertstettner/drone-codecov
    secrets: [codecov_token]
    files:
      - cover/excoveralls.json

services:
  - name: database
    image: postgres:10.6
    environment:
      POSTGRES_DB: dymo_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
